In [2]:
# code here
import numpy as np
import pandas as pd

###`Q-1:` Write a program to create an empty series.

In [3]:
emptylist = []
pd.Series(emptylist)

Series([], dtype: object)

###`Q-2:` Write a Pandas program to add, subtract, multiple and divide two Pandas Series.

In [4]:
runs = [13,24,56,78,100]
marks = [67,57,89,100]
result = pd.DataFrame()

In [8]:

result['add11'] = pd.DataFrame({'add1': pd.Series(runs) + pd.Series(marks)})
result['sub'] = pd.DataFrame({'sub': pd.Series(runs) - pd.Series(marks)})
result['mul'] = pd.DataFrame({'mul': pd.Series(runs) * pd.Series(marks)})
result['div'] = pd.DataFrame({'div': pd.Series(runs) / pd.Series(marks)})

In [7]:
result.dropna()

    add1   sub     mul       div
0   80.0 -54.0   871.0  0.194030
1   81.0 -33.0  1368.0  0.421053
2  145.0 -33.0  4984.0  0.629213
3  178.0 -22.0  7800.0  0.780000

$$result = pd.DataFrame({
     'add': pd.Series(runs) + pd.Series(marks),
    'sub': pd.Series(runs) - pd.Series(marks)
})$$

result = pd.DataFrame()
result['add'] = pd.Series(runs) + pd.Series(marks)
result['sub'] = pd.Series(runs) - pd.Series(marks)

In [15]:
result

     sub
0   80.0
1   81.0
2  145.0
3  178.0
4    NaN

###`Q-3` Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [39]:
S1 = [2, 4, 1, 8, 15]
S2 = [1, 3, 5, 7, 100]
S1=pd.Series(S1)
S2=pd.Series(S2)

S_compare = pd.Series(dtype=bool)
S_compare = S1 > S2
S_compare

0     True
1     True
2    False
3     True
4    False
dtype: bool

###`Q-5.`Write a function to change the data type of given a column or a Series. Function takes series and data type as input, returns the converted series.
```
series = pd.Series([1,2,'Python', 2.0, True, 100])
change to float type data
```
Note: Read about pd.to_numeric()

In [41]:
def convert_dtype(series, dtype):
    return pd.to_numeric(series, errors='coerce').astype(dtype)

series = pd.Series([1,2,'Python', 2.0, True, 100])
result = convert_dtype(series, float)
print(result )

0      1.0
1      2.0
2      NaN
3      2.0
4      1.0
5    100.0
dtype: float64

Download data - https://drive.google.com/file/d/1LRhXwbEodeWXtzPhJCX0X9Lf_BECzvqb/view?usp=share_link
All Batsman runs series in IPL 2008 to 2022.

Below questions are based on this data.

###`Q-6` Find top 10 most run getter from the series.

sort value

In [44]:
batsman_run = pd.read_csv('batsman_runs_series.csv')

batsman_run

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [ ]:
batsman_run.sort_values(by='batsman_run', ascending=False).head(10)

             batter  batsman_run
569         V Kohli         6634
462        S Dhawan         6244
130       DA Warner         5883
430       RG Sharma         5881
493        SK Raina         5536
27   AB de Villiers         5181
108        CH Gayle         4997
339        MS Dhoni         4978
452      RV Uthappa         4954
256      KD Karthik         4377

###`Q-7` No of players having runs above 3000

In [52]:
# code here
under300runs= batsman_run[batsman_run['batsman_run'].between(0,3001)]
under300runs.sort_values(by='batsman_run', ascending=False)

             batter  batsman_run
88      BB McCullum         2882
441         RR Pant         2851
384        PA Patel         2848
219      JC Buttler         2832
513         SS Iyer         2780
..              ...          ...
537     Sunny Gupta            0
102         C Nanda            0
63     Abdur Razzak            0
562          U Kaul            0
570  V Pratap Singh            0

[585 rows x 2 columns]

###`Q-8` No of players having runs above mean value?

S1 = [2, 4, 1, 8, 15]
S2 = [1, 3, 5, 7, 100]
S1=pd.Series(S1)
S2=pd.Series(S2)

S_compare = pd.Series(dtype=bool)
S_compare = S1 > S2
S_compare

In [67]:
# code here
mean_run=batsman_run['batsman_run'].mean()
runs_over_mean = pd.Series()
runs_over_mean = batsman_run[batsman_run['batsman_run'] > mean_run]
runs_over_mean.sort_values(by='batsman_run', ascending=True).head(10)

              batter  batsman_run
337         MR Marsh          476
520      SW Billings          503
387      PC Valthaty          505
371          OA Shah          506
185  Gurkeerat Singh          511
299         M Manhas          514
412          R Parag          522
43        AK Markram          527
237      JP Faulkner          527
446        RS Bopara          531

Download data - https://drive.google.com/file/d/1QZuZ5bypUInfVvarHACLAi8tXXHvb8xd/view?usp=share_link

file name - items.csv

###`Q-9`
    i. Read `items.csv` making `item_name` as index.
    ii. Show no of nan values
    ii. Item price is given in $, so convert it to rupees without currency symbol.
    iii. Make data type of newly made series as float.
    iv. Fill nan with mean of the series


How csv file looks

```
item_name	item_price
Chips and Fresh Tomato Salsa	$2.39
Izze	$3.39
Nantucket Nectar	$3.39
Chips and Tomatillo-Green Chili Salsa	$2.39
Chicken Bowl	$16.98

```

In [ ]:
# code here

###`Q-10`:
    i. Find mean price
    ii. Find 30th and 6th percentile value
    iii. Plot Histogram on price with bin size 50
    iv. No of items price lies between [1000 to 2000]

In [ ]:
# code here