In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import scipy.stats as stats

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

from sklearn.linear_model import LinearRegression

from sklearn.metrics import r2_score

from sklearn.preprocessing import PowerTransformer
from sklearn.preprocessing import OrdinalEncoder

In [3]:
house= pd.read_csv("A:\\AIML_DEV_FOLDER\\Dataset_self\\House Price Prediction Dataset.csv")

In [4]:
house.head()

,ID,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

# check the data for 0 and -ve

In [5]:
house.describe()

,ID,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Price
count,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000
mean,1000.500000,2786.209500,3.003500,2.55250,1.993500,1961.446000,537676.855000
std,577.494589,1295.146799,1.424606,1.10899,0.809188,35.926695,276428.845719
min,1.000000,501.000000,1.000000,1.00000,1.000000,1900.000000,50005.000000
25%,500.750000,1653.000000,2.000000,2.00000,1.000000,1930.000000,300098.000000
50%,1000.500000,2833.000000,3.000000,3.00000,2.000000,1961.000000,539254.000000
75%,1500.250000,3887.500000,4.000000,4.00000,3.000000,1993.000000,780086.000000
max,2000.000000,4999.000000,5.000000,4.00000,3.000000,2023.000000,999656.000000

In [6]:
X = house.drop(columns=['Price'])
y = house.iloc[:,-1] # last colmun ""   --> only strenght is passed here

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.5,random_state=32)

# Note that 1st we have to convert the data in numberical data

# Resolve this we will use Ordinal Encoding

In [17]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:

preprocessor = ColumnTransformer(
    transformers=[
        ('num', 'passthrough', ['YearBuilt']),
        ('loc', OneHotEncoder(drop='first'), ['Location']),
        ('cond', OrdinalEncoder(categories=[['Poor', 'Fair', 'Good', 'Excellent']]), ['Condition']),
        ('garage', OneHotEncoder(drop='if_binary'), ['Garage'])
    ])