In [ ]:
import numpy as np
import pandas as pd  # pandas

In [1]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [5]:
df = pd.read_csv('covid_toy.csv')
df.sample(5)

    age  gender  fever cough     city has_covid
83   17  Female  104.0  Mild  Kolkata        No
80   14  Female   99.0  Mild   Mumbai       Yes
25   23    Male    NaN  Mild   Mumbai        No
69   73  Female  103.0  Mild    Delhi        No
77    8  Female  101.0  Mild  Kolkata        No

# hoW TO SEE YOUR nuLL / Empty VALUES?

In [6]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

# import train test split

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [9]:
X_train

    age  gender  fever   cough       city
50   19    Male  101.0    Mild      Delhi
7    20  Female    NaN  Strong     Mumbai
86   25    Male  104.0    Mild  Bangalore
34   74    Male  102.0    Mild     Mumbai
35   82  Female  102.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
31   83    Male  103.0    Mild    Kolkata
32   34  Female  101.0  Strong      Delhi
67   65    Male   99.0    Mild  Bangalore
26   19  Female  100.0    Mild    Kolkata
37   55    Male  100.0    Mild    Kolkata

[80 rows x 5 columns]

# train test slplit 
    * 100 total 
    * 80 test data
    * 20 test data

# Aam Zindagi

# fill missing data

In [10]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [12]:
X_train_fever # with no missing value 
# replace with mean value

array([[101.        ],
       [100.73239437],
       [104.        ],
       [102.        ],
       [102.        ],
       [101.        ],
       [100.        ],
       [ 99.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [104.        ],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [102.        ],
       [104.        ],
       [100.73239437],
       [102.        ],
       [100.73239437],
       [101.        ],
       [100.73239437],
       [101.        ],
       [104.        ],
       [102.        ],
       [103.        ],
       [102.        ],
       [102.        ],
       [102.        ],
       [100.73239437],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [ 99.        ],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [100.73239437],
       [100.73239437],
       [100.        ],
       [ 98.        ],
       [ 98.        ],
       [100.        ],
       [ 99.        ],
       [ 99.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [101.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [104.        ],
       [103.        ],
       [ 98.        ],
       [100.        ],
       [ 99.        ],
       [ 99.        ],
       [104.        ],
       [103.        ],
       [100.73239437],
       [101.        ],
       [100.        ],
       [ 98.        ],
       [101.        ],
       [100.        ],
       [104.        ],
       [100.73239437],
       [103.        ],
       [101.        ],
       [ 99.        ],
       [100.        ],
       [100.        ]])

In [13]:
# Ordinalencoding -> cough 
# mild --> low 
# STrong --> high 
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']]) # 80 % trained data 

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']]) # 20 % test data

X_train_cough.shape

(80, 1)

# Gender se 1 column 
## city se 3 value

In [15]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [16]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [17]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

# mentos Zindagi

In [18]:
from sklearn.compose import ColumnTransformer

# Create a object 
    * trasnformation of the data
    * you have 2  work
    * either u drop the data or passthough ( leave as it is )

In [19]:
transformer = ColumnTransformer(transformers=[],remainder='passthrough') # 2

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')