In [2]:
import numpy as np
import pandas as pd  # pandas

In [3]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [4]:
df = pd.read_csv('covid_toy.csv')
df.sample(5)

    age  gender  fever   cough       city has_covid
91   38    Male    NaN    Mild      Delhi       Yes
77    8  Female  101.0    Mild    Kolkata        No
8    19  Female  100.0  Strong  Bangalore        No
11   65  Female   98.0    Mild     Mumbai       Yes
32   34  Female  101.0  Strong      Delhi       Yes

# hoW TO SEE YOUR nuLL / Empty VALUES?

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

# import train test split

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [7]:
X_train

    age  gender  fever   cough       city
78   11    Male  100.0    Mild  Bangalore
94   79    Male    NaN  Strong    Kolkata
36   38  Female  101.0    Mild  Bangalore
25   23    Male    NaN    Mild     Mumbai
60   24  Female  102.0  Strong  Bangalore
..  ...     ...    ...     ...        ...
19   42  Female    NaN  Strong  Bangalore
35   82  Female  102.0  Strong  Bangalore
52   47  Female  100.0  Strong  Bangalore
53   83    Male   98.0    Mild      Delhi
56   71    Male    NaN  Strong    Kolkata

[80 rows x 5 columns]

# train test slplit 
    * 100 total 
    * 80 test data
    * 20 test data

# Aam Zindagi

# fill missing data

In [8]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [9]:
X_train_fever # with no missing value 
# replace with mean value

array([[100.        ],
       [100.66666667],
       [101.        ],
       [100.66666667],
       [102.        ],
       [100.        ],
       [101.        ],
       [102.        ],
       [ 99.        ],
       [100.        ],
       [ 98.        ],
       [100.        ],
       [ 98.        ],
       [100.66666667],
       [103.        ],
       [ 98.        ],
       [ 99.        ],
       [ 98.        ],
       [ 99.        ],
       [104.        ],
       [101.        ],
       [103.        ],
       [101.        ],
       [103.        ],
       [100.66666667],
       [100.        ],
       [104.        ],
       [100.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [102.        ],
       [101.        ],
       [101.        ],
       [101.        ],
       [101.        ],
       [101.        ],
       [ 98.        ],
       [104.        ],
       [101.        ],
       [102.        ],
       [ 99.        ],
       [103.        ],
       [104.        ],
       [ 99.        ],
       [104.        ],
       [ 99.        ],
       [ 99.        ],
       [102.        ],
       [ 98.        ],
       [ 99.        ],
       [102.        ],
       [ 99.        ],
       [104.        ],
       [104.        ],
       [102.        ],
       [ 98.        ],
       [103.        ],
       [ 98.        ],
       [100.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [ 99.        ],
       [100.66666667],
       [100.        ],
       [ 98.        ],
       [100.66666667],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [104.        ],
       [104.        ],
       [ 98.        ],
       [101.        ],
       [100.66666667],
       [102.        ],
       [100.        ],
       [ 98.        ],
       [100.66666667]])

In [10]:
# Ordinalencoding -> cough 
# mild --> low 
# STrong --> high 
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']]) # 80 % trained data 

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']]) # 20 % test data

X_train_cough.shape

(80, 1)

# Gender se 1 column 
## city se 3 value

In [11]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [12]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [13]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

# mentos Zindagi

In [14]:
from sklearn.compose import ColumnTransformer

# Create a object 
    * trasnformation of the data
    * you have 2  work
    * either u drop the data or passthough ( leave as it is )

    * Step 2
        * transformer passed in tuple 
        * I will pass 3 tuple tnf1 ... so on 
    * tnf1 --> fill the missing data 
    * tnf2 --> categories=[['Mild','Strong']]),['cough'] ranking of cough  on cough column
    * tnf3 --> OneHotEncoder(sparse=False,drop='first'),['gender','city'])

In [17]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']), # imputer fill ethe 
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [18]:
transformer.fit_transform(X_train).shape

(80, 7)

In [19]:
transformer.transform(X_test).shape

(20, 7)