# binning is a type of technique 
--> where we group data together in range   
    --> such as 1-10, 10-20 etc.  
    --> gogle playstore download example   
    --> this will be used to compute the average value for each variable.

# there are 2 type of bining technique:
 * Disceritization binning 
 * Binarization

#

# Binarization 
data devied in 2 part such 0 , 1 
--> eg -> anual income is 5lpa    
--> if annual income > 5 lpa then it will be assigned as 0   
--> if annual income < 5 lpa then it will be assigned as 1  

#### used in classification problem, Image processing, Data compression etc
 * isme basicaly ham loag ek threshold set karte hai
 * uske badd uss threshold se 0 1 decide hota hai 
 * if threshold > 0 then it will be assigned as 0
 * if threshold < 0 then it will be assigned as 1

# Binning / Descretization 
 * Typical histogram type 
 * simple term me classification of data based on the 
 * divides the shades into different categories.
  12,22,5465,5456,321,6,46,1631,6,43,16,46,3216,46,2,98746,59,76,216,7651,964
  10-50,  50-100, 100-150 etc.

Types of binning 
a. unspervised 
b. supervised
c. custom binning

# unspervised 3 technique 
* uniform binning ( equal binning)
* equal frequency ( Quantile )
* k means binning ( K-Means )

# Supervised
* Decission tree binning

# Custom binning

-------------------------------------------------------

# uniform binning ( equal binning )

# step 1 
 * How to calculate the number of bins ?   
 ->  ( max - min ) / bins     
 ->   min = 0, max = 100, bins =10  == 10 bins  
0-10,10-20,20-30,30-40 etc.

# Note why we do this ?
--> Outlier are handled   
--> NO change in Spread of data

# equal frequency ( Quantile )

 * the catch is that if    
    *  Bin ==  Quantile    
--> if we want 10 bin here   
-->  then we need 10 quantiles for each variable in our data set.  
EG niche wala 
dekhe tho 1 Quantiles me me ek value aayyeg GA

![My Image](./Per.png)

# WHY we do this ?
 * value spread are equal 
 * outlier are handlled care fully

# k Means binning
 * one note document

# Binarization

In [3]:
import numpy as np
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score

from sklearn.compose import ColumnTransformer

In [11]:
df = pd.read_csv('spotify_churn_dataset.csv')[
['age','listening_time','songs_played_per_day','skip_rate','ads_listened_per_week','offline_listening', 
'is_churned']]

# for now i am picking up numberical data only

In [14]:
df.head()

,age,listening_time,songs_played_per_day,skip_rate,ads_listened_per_week,offline_listening,is_churned
0,54,26,23,0.20,31,0,1
1,33,141,62,0.34,0,1,0
2,38,199,38,0.04,0,1,1
3,22,36,2,0.31,0,1,0
4,29,250,57,0.36,0,1,1

 * You can merger 2 column with each other here i won't see that so leave it   
 * df['Tracktime']= df['ofline_listening']+df['ads_listened_per_week']
 * Drop the data df.drop(columns=['SibSp','Parch'],inplace=True)

In [15]:
df.head()

,age,listening_time,songs_played_per_day,skip_rate,ads_listened_per_week,offline_listening,is_churned
0,54,26,23,0.20,31,0,1
1,33,141,62,0.34,0,1,0
2,38,199,38,0.04,0,1,1
3,22,36,2,0.31,0,1,0
4,29,250,57,0.36,0,1,1

# prepare your data for X and Y

In [16]:
X = df.drop(columns=['is_churned']) # is churnmed is only removed 
y = df['is_churned'] # # is churnmed is only added test

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=42)

In [20]:
X_train.head()

,age,listening_time,songs_played_per_day,skip_rate,ads_listened_per_week,offline_listening
238,37,113,85,0.23,27,0
92,57,210,7,0.25,0,1
2977,52,187,94,0.47,0,1
3463,49,54,56,0.39,0,1
3937,31,21,82,0.21,0,1

# Without binarization

In [24]:

clf = DecisionTreeClassifier()

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

accuracy_score(y_test,y_pred)

0.6146875

# cross valadation

In [25]:
np.mean(cross_val_score(DecisionTreeClassifier(),X,y,cv=10, scoring='accuracy'))

np.float64(0.6005)

# applying biniraztion

In [28]:
# Applying Binarization

from sklearn.preprocessing import Binarizer

Create a Tranfromer

In [29]:
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['age','listening_time','songs_played_per_day','skip_rate','ads_listened_per_week','offline_listening'])
],remainder='passthrough')

In [30]:
X_train_trans=trf.fit_transform(X_train)
X_test_trans=trf.fit_transform(X_test)

In [31]:
pd.DataFrame(X_train_trans,columns=['age','listening_time','songs_played_per_day','skip_rate','ads_listened_per_week','offline_listening'])

,age,listening_time,songs_played_per_day,skip_rate,ads_listened_per_week,offline_listening
0,1.0,1.0,1.0,1.0,1.0,0.0
1,1.0,1.0,1.0,1.0,0.0,1.0
2,1.0,1.0,1.0,1.0,0.0,1.0
3,1.0,1.0,1.0,1.0,0.0,1.0
4,1.0,1.0,1.0,1.0,0.0,1.0
...,...,...,...,...,...,...
4795,1.0,1.0,1.0,1.0,0.0,1.0
4796,1.0,1.0,1.0,1.0,0.0,1.0
4797,1.0,1.0,1.0,1.0,0.0,1.0
4798,1.0,1.0,1.0,1.0,0.0,1.0
4799,1.0,1.0,1.0,1.0,0.0,1.0

In [32]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trans,y_train)
y_updated_Pred = clf.predict(X_test_trans)
accuracy_score(y_test,y_updated_Pred)

0.745

In [33]:
X_trf = trf.fit_transform(X)
np.mean(cross_val_score(DecisionTreeClassifier(),X_trf,y,cv=10,scoring='accuracy'))

np.float64(0.741125)