In [1]:
import numpy as np
import pandas as pd

In [2]:
spoti = pd.read_csv('A:/spotify_churn_dataset.csv', nrows=1000)

In [3]:
spoti.sample(15)

,user_id,gender,age,country,subscription_type,listening_time,songs_played_per_day,skip_rate,device_type,ads_listened_per_week,offline_listening,is_churned
981,982,Female,35,PK,Student,48,5,0.44,Web,0,1,0
879,880,Female,50,FR,Premium,207,5,0.30,Desktop,0,1,0
834,835,Male,26,CA,Family,206,5,0.10,Desktop,0,1,0
151,152,Male,58,US,Student,158,52,0.27,Mobile,0,1,0
847,848,Male,39,IN,Student,226,92,0.04,Mobile,0,1,0
919,920,Female,47,AU,Free,208,49,0.30,Mobile,45,0,0
168,169,Male,51,CA,Premium,168,28,0.54,Web,0,1,0
797,798,Female,27,FR,Premium,185,6,0.18,Desktop,0,1,0
653,654,Female,55,CA,Premium,200,50,0.04,Web,0,1,0
332,333,Male,46,CA,Family,152,83,0.58,Mobile,0,1,0
793,794,Male,20,PK,Family,185,79,0.37,Web,0,1,0
422,423,Female,40,AU,Student,281,77,0.38,Web,0,1,0
339,340,Female,55,IN,Family,291,39,0.30,Mobile,0,1,1
748,749,Other,22,AU,Free,276,11,0.13,Desktop,9,0,0
583,584,Female,33,CA,Student,121,41,0.08,Desktop,0,1,0

Take a deep look is there any link between gender and churn rate?   
Is it also with other to churn rate ? 
ALSO TAKE A DEEP LOOK FOR RANK LOOK !

In [4]:
spoti['gender'].value_counts()

gender
Female    341
Other     331
Male      328
Name: count, dtype: int64

# CHECK THE RANK FROM EACH COLUMN !

### Note that ordinal only works for string data.

In [5]:
cat_cols = spoti.select_dtypes(include=['object']).columns # object in pandas = Text/String columns
for col in cat_cols:
    print(f"\n{col}:")
    print(spoti[col].value_counts())

gender:
gender
Female    341
Other     331
Male      328
Name: count, dtype: int64

country:
country
DE    150
AU    133
US    131
UK    123
FR    122
IN    118
CA    113
PK    110
Name: count, dtype: int64

subscription_type:
subscription_type
Premium    294
Free       238
Family     236
Student    232
Name: count, dtype: int64

device_type:
device_type
Desktop    352
Web        331
Mobile     317
Name: count, dtype: int64

In [6]:
# SAME FOR THE 5TH MORE SIMPLE METHOD 
'''
for col in ['age','country','subscription_type','device_type','is_churned']:
    print(f"\n{col} counts:")
    print(spoti[col].value_counts().head(10))  # Top 10 values '''

'\nfor col in [\'age\',\'country\',\'subscription_type\',\'device_type\',\'is_churned\']:\n    print(f"\n{col} counts:")\n    print(spoti[col].value_counts().head(10))  # Top 10 values '

In [7]:
spoti['gender'].value_counts()

gender
Female    341
Other     331
Male      328
Name: count, dtype: int64

# now select the Rows

In [9]:
spoti_Ilocked= spoti.iloc[:, [1, 3, 4, 8]]

In [10]:
spoti_Ilocked.sample(10)

     gender country subscription_type device_type
789    Male      FR           Student         Web
337   Other      AU           Student         Web
784  Female      FR           Premium      Mobile
821  Female      FR              Free      Mobile
606  Female      DE           Student         Web
654  Female      IN           Student     Desktop
386    Male      FR              Free         Web
89    Other      DE           Student     Desktop
603    Male      UK              Free      Mobile
158   Other      AU            Family      Mobile