In [48]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [49]:
df =pd.read_csv("A:\\AIML_DEV_FOLDER\\Dataset_self\\House Price Prediction Dataset.csv")

# Dropped the missing value

In [50]:
df.dropna(inplace=True)

# checking coulmn id

In [51]:
col_name=df.columns
col_name

Index(['ID', 'Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt',
       'Location', 'Condition', 'Garage', 'Price'],
      dtype='object')

In [52]:
for idx,col_name in enumerate(df.columns ):
    print(idx,col_name)

0 ID
1 Area
2 Bedrooms
3 Bathrooms
4 Floors
5 YearBuilt
6 Location
7 Condition
8 Garage
9 Price

In [53]:
df.head()

,ID,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [85]:
from sklearn.preprocessing import OrdinalEncoder

# Encode data

In [104]:
oe = OrdinalEncoder(categories=[['Rural','Downtown','Suburban','Urban'],['Poor','Fair','Excellent'],['No','Yes']])

# Fit the data

# Another approch of data

In [105]:
for idx,col_name in enumerate(df.columns ):
    print(idx,col_name)

0 ID
1 Area
2 Bedrooms
3 Bathrooms
4 Floors
5 YearBuilt
6 Location
7 Condition
8 Garage
9 Price
10 location_en

In [106]:
oe = OrdinalEncoder(categories=[['Rural','Downtown','Suburban','Urban'],['Poor','Good','Fair','Excellent'],['No','Yes']])

In [107]:
oe.fit(df[['Location', 'Condition', 'Garage']])

OrdinalEncoder(categories=[['Rural', 'Downtown', 'Suburban', 'Urban'],
                           ['Poor', 'Good', 'Fair', 'Excellent'],
                           ['No', 'Yes']])

In [109]:
df[['Location', 'Condition', 'Garage']] = oe.transform(df[['Location', 'Condition', 'Garage']])

In [113]:
df.head()

,ID,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price,location_en
0,1,1360,5,4,3,1970,1.0,3.0,0.0,149919,Downtown
1,2,4272,5,4,3,1958,1.0,3.0,0.0,424998,Downtown
2,3,3592,2,2,3,1938,1.0,1.0,0.0,266746,Downtown
3,4,966,4,2,2,1902,2.0,2.0,1.0,244020,Suburban
4,5,4926,1,4,2,1975,1.0,2.0,1.0,636056,Downtown

In [130]:
X = df.iloc[:,0:-2]
y = df.iloc[:,-1]

In [131]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=5))

c:\Users\manis\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\manis\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\manis\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\manis\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\manis\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

np.float64(0.998)

# its got 26.9 %

In [132]:
X.head()

,ID,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage
0,1,1360,5,4,3,1970,1.0,3.0,0.0
1,2,4272,5,4,3,1958,1.0,3.0,0.0
2,3,3592,2,2,3,1938,1.0,1.0,0.0
3,4,966,4,2,2,1902,2.0,2.0,1.0
4,5,4926,1,4,2,1975,1.0,2.0,1.0

In [133]:
X['bhk']=X['Bedrooms']+X['Bathrooms']+X['Floors']
X['bhk']

0       12
1       12
2        7
3        8
4        7
        ..
1995    12
1996     8
1997     8
1998     6
1999     9
Name: bhk, Length: 2000, dtype: int64

In [134]:
X['LCG']=X['Location']+X['Condition']+X['Garage']
X['LCG']

0       4.0
1       4.0
2       2.0
3       5.0
4       4.0
       ...
1995    2.0
1996    3.0
1997    0.0
1998    7.0
1999    4.0
Name: LCG, Length: 2000, dtype: float64

In [135]:
X.drop(columns=['Location','Condition','Garage','Bedrooms','Bathrooms','Floors'],inplace=True)

In [136]:
X.head()

   ID  Area  YearBuilt  bhk  LCG
0   1  1360       1970   12  4.0
1   2  4272       1958   12  4.0
2   3  3592       1938    7  2.0
3   4   966       1902    8  5.0
4   5  4926       1975    7  4.0