In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('train.csv')[['Age','Pclass','Fare','Survived']]

In [3]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [4]:
df.isnull().mean() * 100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [5]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [7]:
X_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

# Knn key points
 * missing_values : int, float, str, np.nan or None, default=np.nan
 The placeholder for the missing values. All occurrences of missing_values will
 be imputed. For pandas'dataframes with nullable integer dtypes with missing
 values, missing_values should be set to np.nan, since pd.NA will be converted
 to np.nan. 
 * n_neighbors : int, deface
 * weights : {'uniform', 'distance') or callable, default: 'uniform'
 * metric :'nan _ euclidean') or callable, default: 'nan _ euclidean'
 * add_indicator : boot, default=False

# code step orginal 
It creates a new pandas DataFrame with the transformed values, keeping the original column structure.

X_train.columns = ['age', 'salary']  
X_test_trf = [[0.5, 1.2]]  

Result DataFrame:  
   age  salary  
0  0.5     1.2

# Step 1 
 * Createa object named with knn
 * now pass the x data for test and traiend
 * *yaha pe hamko har ek nebhiour ke liye loop* 
 * weight = unirom distance

In [10]:
knn = KNNImputer(n_neighbors=3,weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

In [11]:
pd.DataFrame(X_test_trf,columns=X_train.columns)

           Age  Pclass     Fare
0    42.000000     1.0  26.2875
1    21.000000     3.0   8.0500
2    24.000000     2.0  65.0000
3    28.000000     3.0  56.4958
4    17.000000     3.0   7.9250
..         ...     ...      ...
174  24.000000     3.0   8.0500
175  22.000000     3.0   9.0000
176  37.328513     3.0  69.5500
177  26.000000     3.0   7.8958
178  29.000000     3.0  10.4625

[179 rows x 3 columns]

# logistic regression ko call kiya 
 * naya wala data fit kiya
 * predecit kiya hai 
 * accuracy score done

In [12]:
lr = LogisticRegression()

lr.fit(X_train_trf,y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test,y_pred)

0.7039106145251397

# Comparision with Simple Imputer --> mean

In [14]:
# Comparision with Simple Imputer --> mean

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [15]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.6927374301675978

In [ ]:
asdfasd