In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('cars.csv')

In [5]:
df.head(20)
## value counts in a column

       brand  km_driven    fuel         owner  selling_price
0     Maruti     145500  Diesel   First Owner         450000
1      Skoda     120000  Diesel  Second Owner         370000
2      Honda     140000  Petrol   Third Owner         158000
3    Hyundai     127000  Diesel   First Owner         225000
4     Maruti     120000  Petrol   First Owner         130000
5    Hyundai      45000  Petrol   First Owner         440000
6     Maruti     175000     LPG   First Owner          96000
7     Maruti       5000  Petrol  Second Owner          45000
8     Toyota      90000  Diesel   First Owner         350000
9       Ford     169000  Diesel   First Owner         200000
10   Renault      68000  Diesel  Second Owner         500000
11    Maruti     100000  Petrol  Second Owner          92000
12    Maruti     140000  Diesel  Second Owner         280000
13    Maruti      80000  Petrol  Second Owner         200000
14    Maruti      90000  Petrol  Second Owner         180000
15  Mahindra      40000  Petrol   First Owner         400000
16    Maruti      70000  Diesel  Second Owner         778000
17   Hyundai      53000  Diesel  Second Owner         500000
18    Maruti      80000  Petrol  Second Owner         150000
19   Hyundai     100000  Diesel   First Owner         680000

In [6]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

# unique values in a column

In [7]:
df['brand'].nunique()

32

In [8]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [9]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

# One hotEncoding
fuel , owner

In [10]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## 2. K-1 OneHotEncoding 
catagery k-1 and drop= true 
Reason --> both se 1 hata diya hai  10
12 -1 -1  final 10

In [11]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True) 
# these are not permanet changes

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## why not pandas ?
--> pandas not stores where the postion are stored   
--> so that why we use skyit learn

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [16]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [17]:
X_test.head()

         brand  km_driven    fuel         owner
606    Hyundai      80000  Petrol   First Owner
7575  Mahindra      70000  Diesel  Second Owner
7705    Toyota      68089  Petrol   First Owner
4305   Hyundai      70000  Petrol  Second Owner
2685  Mahindra      97000  Diesel  Second Owner

# import preporcessing

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
ohe = OneHotEncoder()

# preforming fir and transfrom

In [66]:
ohe = OneHotEncoder(drop="first",sparse_output=False, dtype=np.int32) # drop 1st data from both 
  # Don't put data here 

ohe.fit(X_train[['fuel','owner']])
 # Put data here

OneHotEncoder(drop='first', dtype=<class 'numpy.int32'>, sparse_output=False)

In [67]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])   # .toarray() not needed if you use spare_ouput = fase

In [68]:
X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [69]:
X_test_new = ohe.transform(X_test[['fuel','owner']]) # .toarray() sparse_output=False

we will append the data

In [70]:
X_train[['brand','km_driven']].values

array([['Hyundai', 35000],
       ['Jeep', 60000],
       ['Hyundai', 25000],
       ...,
       ['Tata', 15000],
       ['Maruti', 32500],
       ['Isuzu', 121000]], dtype=object)

38+40 stack together
uske drop = "first liken dono me ek ek udd gya "

In [71]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new    )).shape

(6502, 9)

In [72]:
X_test_new.shape

(1626, 7)

## 4. OneHotEncoding with Top Categories

In [75]:
counts =df['brand'].value_counts()

In [76]:
df['brand'].nunique()
threshold = 100

In [77]:
repl = counts[counts <= threshold].index

In [78]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3628,False,False,False,False,False,False,True,False,False,False,False,False,False
6510,False,False,False,False,False,False,False,False,False,False,False,True,False
3831,False,False,False,False,False,False,False,False,False,False,False,False,True
2238,False,False,False,False,False,False,False,False,False,True,False,False,False
6444,False,False,False,False,False,False,False,False,False,True,False,False,False